FROM python:3.12.2-slim

ARG path=/app

RUN mkdir $path
WORKDIR $path

COPY ../.env .

ADD genvm $path/genvm
ADD common $path/common

RUN ln genvm/contracts/base.py /tmp/base.py
RUN ln genvm/contracts/llms.py /tmp/llms.py
RUN ln genvm/contracts/context_wrapper.py /tmp/context_wrapper.py
RUN ln genvm/contracts/equivalence_principle.py /tmp/equivalence_principle.py

RUN pip install --no-cache-dir -r genvm/requirements.txt
RUN pip install Flask

ENV PYTHONPATH "${PYTHONPATH}:/${path}"

CMD ["python", "genvm/server.py"]