FROM python:3.12.2-slim

ARG path=/app

RUN mkdir $path
WORKDIR $path

COPY ../.env .
COPY ../logging_config.json .

ADD rpc $path/rpc
ADD database $path/database
ADD consensus $path/consensus
ADD common $path/common

RUN pip install --no-cache-dir -r rpc/requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:/${path}"

CMD ["python", "rpc/server.py"]