FROM python:3.11-slim

ARG path=/app

RUN mkdir $path
WORKDIR $path

COPY ../.env .

ADD rpc $path/rpc
ADD database $path/database
ADD consensus $path/consensus

RUN pip install --no-cache-dir -r rpc/requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:/${path}"

CMD ["python", "rpc/server.py"]