# Use the official PostgreSQL image with Alpine linux from the Docker Hub
FROM postgres:12.19-alpine

# Set the working directory in the container
WORKDIR /docker-entrypoint-initdb.d

# Copy the initialization script or SQL file into the container
# It should be an SQL file or a shell script that runs SQL commands
COPY ./backend/database_handler/initialization/init-db.sql /docker-entrypoint-initdb.d/
