"""rollup_transactions

Revision ID: 1ecaa2085aec
Revises: ab256b41602a
Create Date: 2024-10-22 15:12:02.316347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecaa2085aec'
down_revision: Union[str, None] = 'ab256b41602a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollup_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_', sa.String(length=255), nullable=False),
    sa.Column('to_', sa.String(length=255), nullable=True),
    sa.Column('gas', sa.Integer(), nullable=False),
    sa.Column('gas_price', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('nonce', sa.BigInteger(), server_default=sa.text('(EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000)::BIGINT'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='rollup_transactions_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rollup_transactions')
    # ### end Alembic commands ###
