"""rollup_transactions

Revision ID: 1ecaa2085aec
Revises: ab256b41602a
Create Date: 2024-10-22 15:12:02.316347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "1ecaa2085aec"
down_revision: Union[str, None] = "ab256b41602a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rollup_transactions",
        sa.Column("transaction_hash", sa.String(length=66), nullable=False),
        sa.Column("from_", sa.String(length=255), nullable=False),
        sa.Column("to_", sa.String(length=255), nullable=True),
        sa.Column("gas", sa.Integer(), nullable=False),
        sa.Column("gas_price", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("input", sa.Text(), nullable=False),
        sa.Column("nonce", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("transaction_hash", name="rollup_transactions_pkey"),
        sa.UniqueConstraint("transaction_hash"),
    )
    op.drop_table("transactions_audit")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions_audit",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_hash",
            sa.VARCHAR(length=66),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["transaction_hash"],
            ["transactions.hash"],
            name="transaction_hash_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="transactions_audit_pkey"),
    )
    op.drop_table("rollup_transactions")
    # ### end Alembic commands ###
