"""appeal_failed

Revision ID: 2a4ac5eb9455
Revises: 37196a51038e
Create Date: 2024-11-22 09:48:50.048787

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a4ac5eb9455"
down_revision: Union[str, None] = "37196a51038e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("appeal_failed", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "appeal_failed")
    # ### end Alembic commands ###
