"""add leader_only flag

Revision ID: 3566595124f6
Revises: eb32e4bdb446
Create Date: 2024-09-19 11:39:50.612010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3566595124f6"
down_revision: Union[str, None] = "eb32e4bdb446"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("transactions", sa.Column("leader_only", sa.Boolean(), nullable=True))
    op.execute("UPDATE transactions SET leader_only = false")
    op.alter_column("transactions", "leader_only", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "leader_only")
    # ### end Alembic commands ###
