"""add providers unique constraint

Revision ID: 3bc34e44eb72
Revises: b5acc405bcca
Create Date: 2024-10-11 10:14:05.194224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc34e44eb72'
down_revision: Union[str, None] = 'b5acc405bcca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_provider_model_plugin', 'llm_provider', ['provider', 'model', 'plugin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_provider_model_plugin', 'llm_provider', type_='unique')
    # ### end Alembic commands ###
