"""hardhat

Revision ID: 3fb219d7a814
Revises: 579e86111b36
Create Date: 2024-11-20 09:41:33.865721

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3fb219d7a814"
down_revision: Union[str, None] = "579e86111b36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("ghost_contract_address", sa.String(length=255), nullable=True),
    )
    op.drop_table("rollup_transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "ghost_contract_address")
    op.create_table(
        "rollup_transactions",
        sa.Column(
            "transaction_hash",
            sa.VARCHAR(length=66),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("from_", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("to_", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("gas", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("gas_price", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("value", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("input", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("nonce", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("transaction_hash", name="rollup_transactions_pkey"),
    )
    # ### end Alembic commands ###
