"""add transactions triggers

Revision ID: 41e216c8db98
Revises: 3566595124f6
Create Date: 2024-09-30 15:12:29.273538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e216c8db98'
down_revision: Union[str, None] = '3566595124f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('triggered_by_hash', sa.String(length=66), nullable=True))
    op.create_foreign_key('triggered_by_hash_fkey', 'transactions', 'transactions', ['triggered_by_hash'], ['hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('triggered_by_hash_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'triggered_by_hash')
    # ### end Alembic commands ###
