"""remove client session id from transactions

Revision ID: 579e86111b36
Revises: 37196a51038e
Create Date: 2024-11-08 10:41:56.112444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "579e86111b36"
down_revision: Union[str, None] = "37196a51038e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "client_session_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "client_session_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
