"""init

Revision ID: 953de60a1dd8
Revises:
Create Date: 2024-08-21 09:34:07.525299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "953de60a1dd8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "current_state",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="current_state_pkey"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_address", sa.String(length=255), nullable=True),
        sa.Column("to_address", sa.String(length=255), nullable=True),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "consensus_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("nonce", sa.Integer(), nullable=True),
        sa.Column("value", sa.Numeric(), nullable=True),
        sa.Column("type", sa.Integer(), nullable=True),
        sa.Column("gaslimit", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("r", sa.Integer(), nullable=True),
        sa.Column("s", sa.Integer(), nullable=True),
        sa.Column("v", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "type = ANY (ARRAY[0, 1, 2])", name="transactions_type_check"
        ),
        sa.PrimaryKeyConstraint("id", name="transactions_pkey"),
    )
    op.create_table(
        "validators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stake", sa.Numeric(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("provider", sa.String(length=255), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="validators_pkey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("validators")
    op.drop_table("transactions")
    op.drop_table("current_state")
    # ### end Alembic commands ###
