"""add plugin and plugin_config to validators

Revision ID: 986d9a6b0dda
Revises: db38e78684a8
Create Date: 2024-09-10 14:47:10.730407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "986d9a6b0dda"
down_revision: Union[str, None] = "db38e78684a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "validators", sa.Column("plugin", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "validators",
        sa.Column(
            "plugin_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.alter_column(
        "validators", "provider", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "validators", "model", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "validators", "model", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "validators", "provider", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("validators", "plugin_config")
    op.drop_column("validators", "plugin")
    # ### end Alembic commands ###
