"""add_hash

Revision ID: 99d3f1bc5a08
Revises: d9ddc7436122
Create Date: 2024-09-05 17:03:30.743557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "99d3f1bc5a08"
down_revision: Union[str, None] = "d9ddc7436122"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("hash", sa.String(length=255), nullable=False)
    )
    # TODO: find out why this has not been migrated before
    # op.alter_column(
    #     "transactions",
    #     "status",
    #     existing_type=postgresql.ENUM(
    #         "PENDING",
    #         "CANCELED",
    #         "PROPOSING",
    #         "COMMITTING",
    #         "REVEALING",
    #         "ACCEPTED",
    #         "FINALIZED",
    #         "UNDETERMINED",
    #         name="transaction_status",
    #     ),
    #     nullable=False,
    #     existing_server_default=sa.text("'PENDING'::transaction_status"),
    # )
    op.create_unique_constraint(None, "transactions", ["hash"])
    # op.drop_column('transactions', 'id')
    op.add_column(
        "transactions_audit",
        sa.Column("transaction_hash", sa.String(length=255), nullable=True),
    )
    # op.drop_column('transactions_audit', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('transactions_audit', sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column("transactions_audit", "transaction_hash")
    # op.add_column('transactions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, "transactions", type_="unique")
    # op.alter_column(
    #     "transactions",
    #     "status",
    #     existing_type=postgresql.ENUM(
    #         "PENDING",
    #         "CANCELED",
    #         "PROPOSING",
    #         "COMMITTING",
    #         "REVEALING",
    #         "ACCEPTED",
    #         "FINALIZED",
    #         "UNDETERMINED",
    #         name="transaction_status",
    #     ),
    #     nullable=True,
    #     existing_server_default=sa.text("'PENDING'::transaction_status"),
    # )
    op.drop_column("transactions", "hash")
    # ### end Alembic commands ###
