"""appeal_undetermined

Revision ID: a4a32d27dde2
Revises: 2a4ac5eb9455
Create Date: 2024-11-25 14:49:46.916279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4a32d27dde2"
down_revision: Union[str, None] = "2a4ac5eb9455"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("appeal_undetermined", sa.Boolean(), nullable=True)
    )
    op.execute(
        "UPDATE transactions SET appeal_undetermined = FALSE WHERE appeal_undetermined IS NULL"
    )
    op.alter_column("transactions", "appeal_undetermined", nullable=False)
    op.add_column(
        "transactions",
        sa.Column("timestamp_awaiting_finalization", sa.BigInteger(), nullable=True),
    )
    op.execute(
        "UPDATE transactions SET timestamp_awaiting_finalization = 0 WHERE timestamp_awaiting_finalization IS NULL"
    )
    op.drop_column("transactions", "timestamp_accepted")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "timestamp_accepted", sa.BIGINT(), autoincrement=False, nullable=True
        ),
    )
    op.execute(
        "UPDATE transactions SET timestamp_accepted = 0 WHERE timestamp_accepted IS NULL"
    )
    op.drop_column("transactions", "timestamp_awaiting_finalization")
    op.drop_column("transactions", "appeal_undetermined")
    # ### end Alembic commands ###
