"""remove invalid models

Revision ID: ab256b41602a
Revises: 3bc34e44eb72
Create Date: 2024-10-16 15:34:32.798280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab256b41602a"
down_revision: Union[str, None] = "3bc34e44eb72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    models = [
        "dolphin-2.9-llama3-8b",
        "meta-llama/llama-2-70b-chat",
        "mistralai/mixtral-8x7b-instruct",
        "openhermes-2-yi-34b-gptq",
    ]

    for model in models:
        op.execute("DELETE FROM validators WHERE model = %s", model)
        op.execute("DELETE FROM providers WHERE model = %s", model)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
