"""add transactions triggers

Revision ID: b5acc405bcca
Revises: a32f85df2806
Create Date: 2024-10-03 10:41:45.957685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5acc405bcca"
down_revision: Union[str, None] = "a32f85df2806"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("triggered_by_hash", sa.String(length=66), nullable=True),
    )
    op.create_foreign_key(
        "triggered_by_hash_fkey",
        "transactions",
        "transactions",
        ["triggered_by_hash"],
        ["hash"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("triggered_by_hash_fkey", "transactions", type_="foreignkey")
    op.drop_column("transactions", "triggered_by_hash")
    # ### end Alembic commands ###
