"""id_to_hash

Revision ID: c1810fd38ac8
Revises: d9ddc7436122
Create Date: 2024-09-05 11:04:57.844102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text
import hashlib

# revision identifiers, used by Alembic.
revision: str = "c1810fd38ac8"
down_revision: Union[str, None] = "d9ddc7436122"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def generate_hash(transaction_id):
    # Create a hash based on the transaction ID
    return hashlib.sha256(str(transaction_id).encode()).hexdigest()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("hash", sa.String(length=255), nullable=True)
    )

    # Update existing rows with a hash value
    op.execute(
        """
    UPDATE transactions
    SET hash = encode(sha256(id::text::bytea), 'hex')
    """
    )

    op.alter_column("transactions", "hash", nullable=False)

    op.alter_column(
        "transactions",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "CANCELED",
            "PROPOSING",
            "COMMITTING",
            "REVEALING",
            "ACCEPTED",
            "FINALIZED",
            "UNDETERMINED",
            name="transaction_status",
        ),
        nullable=False,
        existing_server_default=sa.text("'PENDING'::transaction_status"),
    )
    op.drop_column("transactions", "id")
    op.add_column(
        "transactions_audit",
        sa.Column("transaction_hash", sa.String(length=255), nullable=True),
    )
    op.drop_column("transactions_audit", "transaction_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions_audit",
        sa.Column("transaction_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("transactions_audit", "transaction_hash")
    op.add_column(
        "transactions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.alter_column(
        "transactions",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "CANCELED",
            "PROPOSING",
            "COMMITTING",
            "REVEALING",
            "ACCEPTED",
            "FINALIZED",
            "UNDETERMINED",
            name="transaction_status",
        ),
        nullable=True,
        existing_server_default=sa.text("'PENDING'::transaction_status"),
    )
    op.drop_column("transactions", "hash")
    # ### end Alembic commands ###
