"""add providers table

Revision ID: db38e78684a8
Revises: d9ddc7436122
Create Date: 2024-09-04 15:16:11.586574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from sqlalchemy.dialects import postgresql

from backend.database_handler.llm_providers import LLMProviderRegistry

# revision identifiers, used by Alembic.
revision: str = "db38e78684a8"
down_revision: Union[str, None] = "d9ddc7436122"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_provider",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="llm_provider_pkey"),
    )
    # ### end Alembic commands ###
    # Get the connection from Alembic
    bind = op.get_bind()

    # Create a new SQLAlchemy session using the connection
    with sessionmaker(bind=bind)() as session:
        LLMProviderRegistry(session).reset_defaults()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_provider")
    # ### end Alembic commands ###
