"""added balance attribute to accounts

Revision ID: f9636f013003
Revises: d9ddc7436122
Create Date: 2024-09-06 19:04:00.439407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f9636f013003"
down_revision: Union[str, None] = "d9ddc7436122"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("current_state", sa.Column("balance", sa.Integer(), nullable=True))
    op.execute("UPDATE current_state SET balance = 0 WHERE balance IS NULL")
    op.alter_column("current_state", "balance", nullable=False)
    op.create_check_constraint(
        "check_balance_non_negative", "current_state", "balance >= 0"
    )
    op.alter_column(
        "transactions",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "CANCELED",
            "PROPOSING",
            "COMMITTING",
            "REVEALING",
            "ACCEPTED",
            "FINALIZED",
            "UNDETERMINED",
            name="transaction_status",
        ),
        nullable=False,
        existing_server_default=sa.text("'PENDING'::transaction_status"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING",
            "CANCELED",
            "PROPOSING",
            "COMMITTING",
            "REVEALING",
            "ACCEPTED",
            "FINALIZED",
            "UNDETERMINED",
            name="transaction_status",
        ),
        nullable=True,
        existing_server_default=sa.text("'PENDING'::transaction_status"),
    )
    op.drop_column("current_state", "balance")
    # ### end Alembic commands ###
