name: Build Docker Images on MacOS

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-13

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: |
          brew install --cask docker
          brew install docker-compose
          open /Applications/Docker.app
          docker --version

      - name: Install Colima
        run: |
          brew install colima
          colima version
          colima start --cpu 3 --memory 6 --disk 100 --vm-type=qemu --mount-type=sshfs --dns=1.1.1.1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: false