name: Build Docker Images on Multiple OS

on:
  push:

env:
  REGISTRY_IMAGE: user/app

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Prepare (Linux, MacOS)
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
        shell: bash
        if: runner.os != 'windows'

      - name: Prepare (windows)
        run: |
          $platform = "${{ matrix.platform }}"
          Write-Host "PLATFORM_PAIR=$platform" >> $env:GITHUB_ENV
        shell: pwsh
        if: runner.os == 'windows'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Set up MacOS environment
        run: |
          brew install docker
          colima start
        shell: bash
        if: runner.os == 'macos'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Images
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},name-canonical=true,push=false