name: Build Docker Images on MacOS

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Install Docker
        run: |
          brew install --cask docker docker-compose
          open /Applications/Docker.app
          docker --version

      - name: Install Colima
        run: |
          brew install colima
          colima start
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: false